-- Seed canônico do Trilhas Poéticas: categorias, zonas e 12 desafios fáceis/acessíveis.

insert into public.categories(slug,name) values
('arte','Arte'),('cidadania-etica-digital','Cidadania e Ética Digital'),('ciencia-de-dados','Ciência de Dados'),('ifmt','Conhecimentos sobre o IFMT'),
('cultura-regional','Cultura Regional'),('geografia-mt','Geografia de Mato Grosso'),('historia-mt','História de Mato Grosso'),('inteligencia-artificial','Inteligência Artificial'),
('literatura','Literatura'),('logica-tecnologia','Lógica e Tecnologia'),('poesia','Poesia'),('sustentabilidade','Sustentabilidade e Meio Ambiente')
on conflict(slug) do update set name=excluded.name,active=true;

insert into public.zones(slug,name) values
('cantina','Cantina'),('terreo','Térreo'),('primeiro-andar','1º andar'),('externo-opcional','Área externa opcional')
on conflict(slug) do update set name=excluded.name,active=true;

with items(category_slug,prompt,options,correct_value,explanation,simplified_prompt) as (values
('arte','Qual destas opções é uma forma de expressão artística?','[{"label":"Senha de acesso","value":"senha"},{"label":"Pintura","value":"pintura"},{"label":"Planilha de cálculo","value":"planilha"},{"label":"Endereço de internet","value":"url"}]'::jsonb,'pintura','A pintura é uma forma de expressão artística visual.','Qual opção representa uma forma de arte?'),
('cidadania-etica-digital','Qual atitude ajuda a incluir mais pessoas no uso de um site?','[{"label":"Usar somente imagens sem descrição","value":"imagens"},{"label":"Exigir respostas muito rápidas","value":"rapidez"},{"label":"Oferecer texto claro e recursos de acessibilidade","value":"acessibilidade"},{"label":"Usar apenas cores para transmitir informações","value":"cores"}]'::jsonb,'acessibilidade','Texto claro, alternativas equivalentes e recursos de acessibilidade ampliam a participação.','O que torna um site mais acessível para diferentes pessoas?'),
('ciencia-de-dados','Em uma tabela, o que uma coluna normalmente representa?','[{"label":"Uma senha secreta","value":"senha"},{"label":"Uma música","value":"musica"},{"label":"Uma fotografia obrigatória","value":"foto"},{"label":"Uma característica dos registros","value":"caracteristica"}]'::jsonb,'caracteristica','Em dados tabulares, as colunas representam características ou atributos dos registros.','Em uma tabela de dados, para que serve uma coluna?'),
('ifmt','O que significa a sigla IFMT?','[{"label":"Instituto Federal de Educação, Ciência e Tecnologia de Mato Grosso","value":"ifmt"},{"label":"Instituto de Formação Musical e Teatro","value":"musica"},{"label":"Instituição Federal de Matemática e Turismo","value":"turismo"},{"label":"Instituto de Fotografia de Mato Grosso","value":"foto"}]'::jsonb,'ifmt','IFMT significa Instituto Federal de Educação, Ciência e Tecnologia de Mato Grosso.','Qual é o nome completo do IFMT?'),
('cultura-regional','Qual manifestação cultural tradicional está associada a Mato Grosso?','[{"label":"Flamenco","value":"flamenco"},{"label":"Ópera italiana","value":"opera"},{"label":"Siriri","value":"siriri"},{"label":"Dança irlandesa","value":"irlandesa"}]'::jsonb,'siriri','O siriri é uma manifestação tradicional da cultura mato-grossense.','Qual destas manifestações faz parte da cultura tradicional de Mato Grosso?'),
('geografia-mt','Qual destes biomas está presente em Mato Grosso?','[{"label":"Tundra","value":"tundra"},{"label":"Taiga","value":"taiga"},{"label":"Deserto do Saara","value":"saara"},{"label":"Pantanal","value":"pantanal"}]'::jsonb,'pantanal','O Pantanal está presente em Mato Grosso e Mato Grosso do Sul.','Qual bioma brasileiro existe em Mato Grosso?'),
('historia-mt','Qual atividade teve importância na formação de Cuiabá no período colonial?','[{"label":"Produção de petróleo","value":"petroleo"},{"label":"Exploração de ouro","value":"ouro"},{"label":"Indústria automobilística","value":"automoveis"},{"label":"Construção naval oceânica","value":"naval"}]'::jsonb,'ouro','A exploração de ouro teve papel importante na ocupação colonial da região de Cuiabá.','Qual atividade ajudou no surgimento de Cuiabá no período colonial?'),
('inteligencia-artificial','Qual frase descreve melhor uma Inteligência Artificial?','[{"label":"Uma pessoa dentro do computador","value":"pessoa"},{"label":"Um tipo de cabo de internet","value":"cabo"},{"label":"Uma bateria especial","value":"bateria"},{"label":"Um sistema capaz de executar tarefas usando modelos e dados","value":"sistema"}]'::jsonb,'sistema','Sistemas de IA utilizam modelos, regras e dados para realizar determinadas tarefas.','O que é uma Inteligência Artificial?'),
('literatura','Quem escreve uma obra literária é chamado de quê?','[{"label":"Autor ou autora","value":"autor"},{"label":"Leitor de código","value":"codigo"},{"label":"Navegador","value":"navegador"},{"label":"Sensor","value":"sensor"}]'::jsonb,'autor','Autor ou autora é a pessoa responsável pela criação de uma obra literária.','Como chamamos a pessoa que escreve uma obra literária?'),
('logica-tecnologia','O que é um algoritmo?','[{"label":"Uma cor de tela","value":"cor"},{"label":"Um tipo de cadeira","value":"cadeira"},{"label":"Uma sequência organizada de passos para realizar uma tarefa","value":"passos"},{"label":"Uma senha obrigatória","value":"senha"}]'::jsonb,'passos','Um algoritmo é uma sequência organizada de instruções ou passos para resolver um problema ou realizar uma tarefa.','Qual opção explica o que é um algoritmo?'),
('poesia','Como se chama cada linha de um poema?','[{"label":"Verso","value":"verso"},{"label":"Capítulo","value":"capitulo"},{"label":"Tabela","value":"tabela"},{"label":"Legenda técnica","value":"legenda"}]'::jsonb,'verso','Cada linha de um poema é chamada de verso.','Qual é o nome de uma linha de um poema?'),
('sustentabilidade','Qual atitude ajuda a reduzir a quantidade de resíduos?','[{"label":"Descartar objetos que ainda podem ser usados","value":"descartar"},{"label":"Reutilizar materiais quando possível","value":"reutilizar"},{"label":"Misturar todos os resíduos de propósito","value":"misturar"},{"label":"Comprar itens sem necessidade","value":"comprar"}]'::jsonb,'reutilizar','Reutilizar materiais prolonga sua vida útil e pode reduzir a geração de resíduos.','Qual ação pode ajudar a produzir menos lixo?')
)
insert into public.questions(category_id,kind,prompt,options,correct_answer,explanation,difficulty,accessibility,active)
select c.id,'multiple_choice',i.prompt,i.options,jsonb_build_object('value',i.correct_value),i.explanation,1,
  jsonb_build_object('reading_level','básica','requires_speed',false,'equivalent_text',true,'simplified_prompt',i.simplified_prompt,'instructions_clear',true,'screen_reader_ready',true,'depends_on_color_only',false),true
from items i join public.categories c on c.slug=i.category_slug
where not exists(select 1 from public.questions q where q.prompt=i.prompt);
